name: setup-archipelo
description: Setup Archipelo CLI on GitHub Actions runners
inputs:
  version:
    description: Version of Archipelo CLI to install
    required: false
    default: v0.6.86
  qa:
    required: false
    description: Point to QA? Only for testing
runs:
  using: node12
  main: dist/index.js
