name: Tests

on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Archipelo
        uses: ./

      - name: Show folder
        run: ls -lsa

      - name: Capture archipelo version installed
        run: |
          export AR_VERSION=$( archipelo version )
          echo 'AR_VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
          archipelo version >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Verify
        shell: python
        env:
          AR_VERSION_EXPECTED: v0.6.86
        run: |
          import sys, os
          sys.exit(
              int(not os.environ["AR_VERSION_EXPECTED"] in os.environ["AR_VERSION_INSTALLED"])
          )
